#!/usr/bin/env bash
# shellcheck disable=SC2154
# Configure Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”
# have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo service nginx start

sudo mkdir -p /var/www/html
sudo touch /var/www/html/index.html
echo "Holberton School" | sudo tee /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     add_header X-Served-By $HOSTNAME;
     root        /var/www/html;
     index       index.html index.htm;
     location /redirect_me {
     	      return 301 http://www.staggeringbeauty.com/;
	      }
     error_page 404 /404.html;
     location /404 {
       root /var/www/html;
       internal;
    }
}
" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
