#!/usr/bin/env bash
# use the transfer file script in my 1628-web-02 server home dir
# name of file to tranfer is currently some_page.html

./0-transfer_file  some_page.html 54.147.176.180 ubuntu ~/.ssh/holberton
