#!/usr/bin/env bash
# use the transfer file script in my 1628-web-01 server home dir
# name of file to tranfer is currently 0-custom_http_response-header
# execute the file to test if it works
# after install deletes the file

./0-transfer_file 0-custom_http_response-header 34.74.73.44 ubuntu ~/.ssh/holberton
ssh ubuntu@34.74.73.44 -i ~/.ssh/holberton './0-custom_http_response-header'
ssh ubuntu@34.74.73.44 -i ~/.ssh/holberton 'rm 0-custom_http_response-header'
