#!/usr/bin/env bash
#Write a Bash script that displays Holberton School 10 times,
#but for the 9th iteration, displays Holberton School and then Hi on a new line.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Holberton School"
  (( count++ ))
done
